[features]
seeds = false
skip-lint = false
[programs.localnet]
loot_goblin = "9yCzP1smsGZmbNyTn87bgLM8wGdj5GcomXZHfQ8JXggZ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/jozanza/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
